### ISSUE TITLE
Hi is this porject still on

### ISSUE THREAD

**Issue by Raj2032** [tomasz1986/classic2000#1]
Hi is this porject still on

**Comment by tomasz1986** [comment]
Yes, I'd assume the files are compatible even with Windows 11.

The themes themselves are based on what was used in Windows 2000, so there's no need to make any changes to the colours.

**Comment by Raj2032** [comment]
@tomasz1986 Would it use less RAM compared to using the default theme in Windows 10?

**Comment by tomasz1986** [comment]
No, not really. This was true in Windows 7 and older, where high contrast themes were based on the classic theme, but starting from Windows 8 and higher, these themes are more like just a different skin on top of the default theme. In other words, you use them because because of either accessibility or esthetical reasons rather than to gain any performance benefits.

**Comment by Raj2032** [comment]
@tomasz1986 AH right what shame, thanks though mate :)
